language: java
jdk:
- openjdk8
sudo: required
before_deploy: mvn clean verify
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: AKIAZOKKB636GOXML5BE
  secret_access_key:
    secure: "m2pLbhytAmVF1J3/q9Ix+0722le/+1JNQp5AnxDdZ4pxr8RCEzweUsgP/JOgrgLG92lZ2WHjRqxjqcVhPUBRRRjJKdD2l7sBOL1Wi9MvmTL7mCDens9QEifyclHld7kSkWB9URe6Mp90GkdVNcFHEBBdrqgUYtMkxrBX+wiYeFE="
  region: us-east-1
  app: bridge-exporter-$TRAVIS_BRANCH-application
  env: bridge-exporter-$TRAVIS_BRANCH
  bucket_name: elasticbeanstalk-us-east-1-649232250620
  zip-file: target/Bridge-Exporter-2.0.war
  on:
    all_branches: true
